version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=desafio03
    volumes:
      - ./data:/var/lib/postgresql/data
