version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: ./path/to/your/Dockerfile
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=desafio03
    volumes:
      - ./data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=pgcrypto", "-c", "max_connections=300"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
      timeout: 10s
